### PR TITLE
Minor overview documentation cleanups.

### PR DESCRIPTION
**Pull request by jasone**

### CODE REVIEW

**Comment by vjeux** [comment]
<3

**Comment by jasone** [comment]
Resolved conflicts with overlapping fixes.

**Comment by vjeux** [comment]
Feel free to merge :)

**Comment by jasone** [comment]
D'oh, my write permission wasn't transferred from the previous repo, and it appears this repo isn't configured to allow contributors to merge approved pull requests.

**Comment by vjeux** [comment]
Arg. I’ll give you write access tomorrow, sorry about it

**Pull request merged**
